Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'

Documentation:
  Enabled: false
